name: "Default smart-team Label"
on: pull_request

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: KeisukeYamashita/attach-labels@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "smart-team"