name: 'Auto Assign'
on: pull_request

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
      - uses: Renato66/auto-label@v2
      with:
        default-labels: '["smart-team"]'